name: ai-bias-audit
channels:
  - conda-forge
dependencies:
  - python=3.10.14
  - pandas=2.2.2
  - scikit-learn=1.5.0
  - fairlearn=0.10.0
  - aif360=0.6.1
  - shap=0.45.0
  - nltk=3.8.1
  - matplotlib=3.8.*
  - streamlit=1.34.0
  - rich=13.7.1
  - typer=0.12.3
  - pyyaml=6.0.1
  - python-dotenv=1.0.1
  - joblib=1.4.2
  - pytest=8.2.0
  - tqdm=4.66.4
  - requests=2.32.3
